### ISSUE TITLE
license is missing

### ISSUE THREAD

**Issue by matkoniecz** [trishume/indexView#3]
Is keeping this project fully copyrighted intentional? Note that without license default status is "all rights reserved" what makes tweaking/improving illegal and/or pointless.

**Comment by trishume** [comment]
Ooops, thanks for the notice. I try to include license files in all my projects that people might care about, but I occasionally forget.

I'm lucky I haven't got and accepted any pull requests yet while there wasn't a license, as far as I understand adding a license after that would be legally iffy.

**Comment by trishume** [comment]
I released it under the MIT license in cc0996867a3064363008bfab72e1cb0ba5b0b574

**Comment by matkoniecz** [comment]
Thanks!
